// User
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_RESPONSE = 'LOGIN_USER_RESPONSE';
export const POST_JOB = 'POST_JOB';
export const GET_JOB = 'GET_JOB';
export const GET_JOB_RESPONSE = 'GET_JOB_RESPONSE';
export const GET_RESOURCE = 'GET_RESOURCE';
export const GET_RESOURCE_RESPONSE = 'GET_RESOURCE_RESPONSE';
export const GET_BILLING_DETAILS = 'GET_BILLING_DETAILS';
export const GET_BILLING_DETAILS_RESPONSE = 'GET_BILLING_DETAILS_RESPONSE';
export const POST_CONTACT_INFO = 'POST_CONTACT_INFO';
export const POST_CONTACT_INFO_RESPONSE = 'POST_CONTACT_INFO_RESPONSE';
export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';
export const SCHEDULE_DEMO = 'SCHEDULE_DEMO';
export const SCHEDULE_DEMO_RESPONSE = 'SCHEDULE_DEMO_RESPONSE';